// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"
import type { NextRequest } from 'next/server.js'

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  POST?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PUT?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PATCH?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  DELETE?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  HEAD?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  OPTIONS?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
}


// Validate ../../../src/app/about/[...slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/about/[...slug]">> = Specific
  const handler = {} as typeof import("../../../src/app/about/[...slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/about/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/about">> = Specific
  const handler = {} as typeof import("../../../src/app/about/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/accessibility/[...slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/accessibility/[...slug]">> = Specific
  const handler = {} as typeof import("../../../src/app/accessibility/[...slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/accessibility/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/accessibility">> = Specific
  const handler = {} as typeof import("../../../src/app/accessibility/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/admin/[...slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/[...slug]">> = Specific
  const handler = {} as typeof import("../../../src/app/admin/[...slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/admin/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin">> = Specific
  const handler = {} as typeof import("../../../src/app/admin/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/ai/[...slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/ai/[...slug]">> = Specific
  const handler = {} as typeof import("../../../src/app/ai/[...slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/ai/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/ai">> = Specific
  const handler = {} as typeof import("../../../src/app/ai/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/auth/signin/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/auth/signin">> = Specific
  const handler = {} as typeof import("../../../src/app/auth/signin/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/auth/signup/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/auth/signup">> = Specific
  const handler = {} as typeof import("../../../src/app/auth/signup/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/automation/[...slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/automation/[...slug]">> = Specific
  const handler = {} as typeof import("../../../src/app/automation/[...slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/automation/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/automation">> = Specific
  const handler = {} as typeof import("../../../src/app/automation/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/blog/[...slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/blog/[...slug]">> = Specific
  const handler = {} as typeof import("../../../src/app/blog/[...slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/blog/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/blog">> = Specific
  const handler = {} as typeof import("../../../src/app/blog/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/brand/[...slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/brand/[...slug]">> = Specific
  const handler = {} as typeof import("../../../src/app/brand/[...slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/brand/arc-panel-lab/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/brand/arc-panel-lab">> = Specific
  const handler = {} as typeof import("../../../src/app/brand/arc-panel-lab/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/brand/aurora-logo-studio/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/brand/aurora-logo-studio">> = Specific
  const handler = {} as typeof import("../../../src/app/brand/aurora-logo-studio/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/brand/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/brand">> = Specific
  const handler = {} as typeof import("../../../src/app/brand/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/brand/photoshop-canvas-advanced/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/brand/photoshop-canvas-advanced">> = Specific
  const handler = {} as typeof import("../../../src/app/brand/photoshop-canvas-advanced/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/brand/photoshop-canvas/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/brand/photoshop-canvas">> = Specific
  const handler = {} as typeof import("../../../src/app/brand/photoshop-canvas/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/brand/photoshop-enhanced/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/brand/photoshop-enhanced">> = Specific
  const handler = {} as typeof import("../../../src/app/brand/photoshop-enhanced/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/brand/photoshop-pro/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/brand/photoshop-pro">> = Specific
  const handler = {} as typeof import("../../../src/app/brand/photoshop-pro/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/brand/studio-pro/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/brand/studio-pro">> = Specific
  const handler = {} as typeof import("../../../src/app/brand/studio-pro/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/brand/universe-logos/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/brand/universe-logos">> = Specific
  const handler = {} as typeof import("../../../src/app/brand/universe-logos/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/commerce/cart/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/commerce/cart">> = Specific
  const handler = {} as typeof import("../../../src/app/commerce/cart/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/commerce/checkout/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/commerce/checkout">> = Specific
  const handler = {} as typeof import("../../../src/app/commerce/checkout/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/commerce/delivery/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/commerce/delivery">> = Specific
  const handler = {} as typeof import("../../../src/app/commerce/delivery/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/commerce/orders/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/commerce/orders/[id]">> = Specific
  const handler = {} as typeof import("../../../src/app/commerce/orders/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/commerce/orders/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/commerce/orders">> = Specific
  const handler = {} as typeof import("../../../src/app/commerce/orders/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/commerce/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/commerce">> = Specific
  const handler = {} as typeof import("../../../src/app/commerce/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/commerce/review/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/commerce/review">> = Specific
  const handler = {} as typeof import("../../../src/app/commerce/review/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/communities/[...slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/communities/[...slug]">> = Specific
  const handler = {} as typeof import("../../../src/app/communities/[...slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/communities/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/communities/[id]">> = Specific
  const handler = {} as typeof import("../../../src/app/communities/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/communities/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/communities">> = Specific
  const handler = {} as typeof import("../../../src/app/communities/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/contact/[...slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/contact/[...slug]">> = Specific
  const handler = {} as typeof import("../../../src/app/contact/[...slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/contact/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/contact">> = Specific
  const handler = {} as typeof import("../../../src/app/contact/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/create/[...slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/create/[...slug]">> = Specific
  const handler = {} as typeof import("../../../src/app/create/[...slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/create/editor/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/create/editor">> = Specific
  const handler = {} as typeof import("../../../src/app/create/editor/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/create/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/create">> = Specific
  const handler = {} as typeof import("../../../src/app/create/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/dashboard/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard">> = Specific
  const handler = {} as typeof import("../../../src/app/dashboard/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/dev/analytics/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dev/analytics">> = Specific
  const handler = {} as typeof import("../../../src/app/dev/analytics/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/dev/arc-panel-lab/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dev/arc-panel-lab">> = Specific
  const handler = {} as typeof import("../../../src/app/dev/arc-panel-lab/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/dev/buttons/advanced/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dev/buttons/advanced">> = Specific
  const handler = {} as typeof import("../../../src/app/dev/buttons/advanced/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/dev/buttons/aurora-enhanced/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dev/buttons/aurora-enhanced">> = Specific
  const handler = {} as typeof import("../../../src/app/dev/buttons/aurora-enhanced/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/dev/buttons/emotional/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dev/buttons/emotional">> = Specific
  const handler = {} as typeof import("../../../src/app/dev/buttons/emotional/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/dev/buttons/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dev/buttons">> = Specific
  const handler = {} as typeof import("../../../src/app/dev/buttons/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/dev/buttons/ultimate/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dev/buttons/ultimate">> = Specific
  const handler = {} as typeof import("../../../src/app/dev/buttons/ultimate/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/dev/diagnostics/[type]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dev/diagnostics/[type]">> = Specific
  const handler = {} as typeof import("../../../src/app/dev/diagnostics/[type]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/dev/diagnostics/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dev/diagnostics">> = Specific
  const handler = {} as typeof import("../../../src/app/dev/diagnostics/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/dev/logo-chain-segment/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dev/logo-chain-segment">> = Specific
  const handler = {} as typeof import("../../../src/app/dev/logo-chain-segment/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/dev/logo-console/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dev/logo-console">> = Specific
  const handler = {} as typeof import("../../../src/app/dev/logo-console/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/dev/logo-modal-routes/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dev/logo-modal-routes">> = Specific
  const handler = {} as typeof import("../../../src/app/dev/logo-modal-routes/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/dev/logo-modal/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dev/logo-modal">> = Specific
  const handler = {} as typeof import("../../../src/app/dev/logo-modal/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/dev/logo-preview/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dev/logo-preview">> = Specific
  const handler = {} as typeof import("../../../src/app/dev/logo-preview/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/dev/logo-ring-engine/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dev/logo-ring-engine">> = Specific
  const handler = {} as typeof import("../../../src/app/dev/logo-ring-engine/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/developer/[...slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/developer/[...slug]">> = Specific
  const handler = {} as typeof import("../../../src/app/developer/[...slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/developer/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/developer">> = Specific
  const handler = {} as typeof import("../../../src/app/developer/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/docs/[[...path]]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/docs/[[...path]]">> = Specific
  const handler = {} as typeof import("../../../src/app/docs/[[...path]]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/economy/[...slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/economy/[...slug]">> = Specific
  const handler = {} as typeof import("../../../src/app/economy/[...slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/economy/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/economy">> = Specific
  const handler = {} as typeof import("../../../src/app/economy/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/entertainment/[...slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/entertainment/[...slug]">> = Specific
  const handler = {} as typeof import("../../../src/app/entertainment/[...slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/entertainment/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/entertainment">> = Specific
  const handler = {} as typeof import("../../../src/app/entertainment/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/finance/[...slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/finance/[...slug]">> = Specific
  const handler = {} as typeof import("../../../src/app/finance/[...slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/finance/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/finance">> = Specific
  const handler = {} as typeof import("../../../src/app/finance/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/gaming/[...slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/gaming/[...slug]">> = Specific
  const handler = {} as typeof import("../../../src/app/gaming/[...slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/gaming/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/gaming">> = Specific
  const handler = {} as typeof import("../../../src/app/gaming/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/guilds/[...slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/guilds/[...slug]">> = Specific
  const handler = {} as typeof import("../../../src/app/guilds/[...slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/guilds/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/guilds">> = Specific
  const handler = {} as typeof import("../../../src/app/guilds/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/health/[...slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/health/[...slug]">> = Specific
  const handler = {} as typeof import("../../../src/app/health/[...slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/health/human-model/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/health/human-model">> = Specific
  const handler = {} as typeof import("../../../src/app/health/human-model/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/health/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/health">> = Specific
  const handler = {} as typeof import("../../../src/app/health/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/home/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/home">> = Specific
  const handler = {} as typeof import("../../../src/app/home/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/homecontrol/[...slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/homecontrol/[...slug]">> = Specific
  const handler = {} as typeof import("../../../src/app/homecontrol/[...slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/homecontrol/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/homecontrol">> = Specific
  const handler = {} as typeof import("../../../src/app/homecontrol/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/identity/[...slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/identity/[...slug]">> = Specific
  const handler = {} as typeof import("../../../src/app/identity/[...slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/identity/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/identity">> = Specific
  const handler = {} as typeof import("../../../src/app/identity/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/learning/[...slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/learning/[...slug]">> = Specific
  const handler = {} as typeof import("../../../src/app/learning/[...slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/learning/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/learning">> = Specific
  const handler = {} as typeof import("../../../src/app/learning/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/legal/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/legal">> = Specific
  const handler = {} as typeof import("../../../src/app/legal/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/luma/[...slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/luma/[...slug]">> = Specific
  const handler = {} as typeof import("../../../src/app/luma/[...slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/luma/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/luma">> = Specific
  const handler = {} as typeof import("../../../src/app/luma/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/navigation/[...slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/navigation/[...slug]">> = Specific
  const handler = {} as typeof import("../../../src/app/navigation/[...slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/navigation/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/navigation">> = Specific
  const handler = {} as typeof import("../../../src/app/navigation/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/navigation/topology/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/navigation/topology">> = Specific
  const handler = {} as typeof import("../../../src/app/navigation/topology/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/notifications/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/notifications">> = Specific
  const handler = {} as typeof import("../../../src/app/notifications/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../../src/app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/product/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/product">> = Specific
  const handler = {} as typeof import("../../../src/app/product/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/productivity/[...slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/productivity/[...slug]">> = Specific
  const handler = {} as typeof import("../../../src/app/productivity/[...slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/productivity/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/productivity">> = Specific
  const handler = {} as typeof import("../../../src/app/productivity/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/profile/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/profile">> = Specific
  const handler = {} as typeof import("../../../src/app/profile/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/realms/[...slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/realms/[...slug]">> = Specific
  const handler = {} as typeof import("../../../src/app/realms/[...slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/realms/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/realms">> = Specific
  const handler = {} as typeof import("../../../src/app/realms/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/roadmap/[...slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/roadmap/[...slug]">> = Specific
  const handler = {} as typeof import("../../../src/app/roadmap/[...slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/roadmap/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/roadmap">> = Specific
  const handler = {} as typeof import("../../../src/app/roadmap/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/security/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/security">> = Specific
  const handler = {} as typeof import("../../../src/app/security/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/settings/[...slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/settings/[...slug]">> = Specific
  const handler = {} as typeof import("../../../src/app/settings/[...slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/settings/change-password/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/settings/change-password">> = Specific
  const handler = {} as typeof import("../../../src/app/settings/change-password/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/settings/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/settings">> = Specific
  const handler = {} as typeof import("../../../src/app/settings/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/settings/profile/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/settings/profile">> = Specific
  const handler = {} as typeof import("../../../src/app/settings/profile/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/social/[...slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/social/[...slug]">> = Specific
  const handler = {} as typeof import("../../../src/app/social/[...slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/social/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/social">> = Specific
  const handler = {} as typeof import("../../../src/app/social/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/travel/[...slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/travel/[...slug]">> = Specific
  const handler = {} as typeof import("../../../src/app/travel/[...slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/travel/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/travel">> = Specific
  const handler = {} as typeof import("../../../src/app/travel/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/analytics/events/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/analytics/events">> = Specific
  const handler = {} as typeof import("../../../src/app/api/analytics/events/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/analytics/metrics/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/analytics/metrics">> = Specific
  const handler = {} as typeof import("../../../src/app/api/analytics/metrics/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/auth/[...nextauth]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/[...nextauth]">> = Specific
  const handler = {} as typeof import("../../../src/app/api/auth/[...nextauth]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/auth/[auth]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/[auth]">> = Specific
  const handler = {} as typeof import("../../../src/app/api/auth/[auth]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/auth/register/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/register">> = Specific
  const handler = {} as typeof import("../../../src/app/api/auth/register/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/brand/brands/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/brand/brands/[id]">> = Specific
  const handler = {} as typeof import("../../../src/app/api/brand/brands/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/brand/brands/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/brand/brands">> = Specific
  const handler = {} as typeof import("../../../src/app/api/brand/brands/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/commerce/products/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/commerce/products/[id]">> = Specific
  const handler = {} as typeof import("../../../src/app/api/commerce/products/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/commerce/products/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/commerce/products">> = Specific
  const handler = {} as typeof import("../../../src/app/api/commerce/products/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/communities/[id]/messages/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/communities/[id]/messages">> = Specific
  const handler = {} as typeof import("../../../src/app/api/communities/[id]/messages/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/communities/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/communities/[id]">> = Specific
  const handler = {} as typeof import("../../../src/app/api/communities/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/communities/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/communities">> = Specific
  const handler = {} as typeof import("../../../src/app/api/communities/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/dev/diagnostics/[type]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/dev/diagnostics/[type]">> = Specific
  const handler = {} as typeof import("../../../src/app/api/dev/diagnostics/[type]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/dev/diagnostics/alerts/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/dev/diagnostics/alerts">> = Specific
  const handler = {} as typeof import("../../../src/app/api/dev/diagnostics/alerts/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/dev/diagnostics/compare/history/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/dev/diagnostics/compare/history">> = Specific
  const handler = {} as typeof import("../../../src/app/api/dev/diagnostics/compare/history/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/dev/diagnostics/compare/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/dev/diagnostics/compare">> = Specific
  const handler = {} as typeof import("../../../src/app/api/dev/diagnostics/compare/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/dev/diagnostics/details/[type]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/dev/diagnostics/details/[type]">> = Specific
  const handler = {} as typeof import("../../../src/app/api/dev/diagnostics/details/[type]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/dev/diagnostics/editor-runtime/export/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/dev/diagnostics/editor-runtime/export">> = Specific
  const handler = {} as typeof import("../../../src/app/api/dev/diagnostics/editor-runtime/export/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/dev/diagnostics/editor-runtime/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/dev/diagnostics/editor-runtime">> = Specific
  const handler = {} as typeof import("../../../src/app/api/dev/diagnostics/editor-runtime/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/dev/diagnostics/history/[type]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/dev/diagnostics/history/[type]">> = Specific
  const handler = {} as typeof import("../../../src/app/api/dev/diagnostics/history/[type]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/dev/diagnostics/readiness/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/dev/diagnostics/readiness">> = Specific
  const handler = {} as typeof import("../../../src/app/api/dev/diagnostics/readiness/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/dev/diagnostics/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/dev/diagnostics">> = Specific
  const handler = {} as typeof import("../../../src/app/api/dev/diagnostics/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/dev/diagnostics/scheduler/export/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/dev/diagnostics/scheduler/export">> = Specific
  const handler = {} as typeof import("../../../src/app/api/dev/diagnostics/scheduler/export/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/dev/diagnostics/scheduler/run/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/dev/diagnostics/scheduler/run">> = Specific
  const handler = {} as typeof import("../../../src/app/api/dev/diagnostics/scheduler/run/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/docs/[...path]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/docs/[...path]">> = Specific
  const handler = {} as typeof import("../../../src/app/api/docs/[...path]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/entertainment/playlists/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/entertainment/playlists/[id]">> = Specific
  const handler = {} as typeof import("../../../src/app/api/entertainment/playlists/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/entertainment/playlists/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/entertainment/playlists">> = Specific
  const handler = {} as typeof import("../../../src/app/api/entertainment/playlists/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/fulfillment/rates/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/fulfillment/rates">> = Specific
  const handler = {} as typeof import("../../../src/app/api/fulfillment/rates/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/fulfillment/returns/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/fulfillment/returns">> = Specific
  const handler = {} as typeof import("../../../src/app/api/fulfillment/returns/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/fulfillment/shipments/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/fulfillment/shipments">> = Specific
  const handler = {} as typeof import("../../../src/app/api/fulfillment/shipments/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/fulfillment/tracking/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/fulfillment/tracking">> = Specific
  const handler = {} as typeof import("../../../src/app/api/fulfillment/tracking/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/health/db/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/health/db">> = Specific
  const handler = {} as typeof import("../../../src/app/api/health/db/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/health/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/health">> = Specific
  const handler = {} as typeof import("../../../src/app/api/health/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/invoices/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/invoices/[id]">> = Specific
  const handler = {} as typeof import("../../../src/app/api/invoices/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/invoices/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/invoices">> = Specific
  const handler = {} as typeof import("../../../src/app/api/invoices/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/learning/courses/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/learning/courses/[id]">> = Specific
  const handler = {} as typeof import("../../../src/app/api/learning/courses/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/learning/courses/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/learning/courses">> = Specific
  const handler = {} as typeof import("../../../src/app/api/learning/courses/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/notifications/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/notifications/[id]">> = Specific
  const handler = {} as typeof import("../../../src/app/api/notifications/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/notifications/mark-all-read/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/notifications/mark-all-read">> = Specific
  const handler = {} as typeof import("../../../src/app/api/notifications/mark-all-read/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/notifications/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/notifications">> = Specific
  const handler = {} as typeof import("../../../src/app/api/notifications/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/payments/confirm/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/payments/confirm">> = Specific
  const handler = {} as typeof import("../../../src/app/api/payments/confirm/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/payments/intents/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/payments/intents">> = Specific
  const handler = {} as typeof import("../../../src/app/api/payments/intents/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/payments/methods/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/payments/methods">> = Specific
  const handler = {} as typeof import("../../../src/app/api/payments/methods/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/payments/refunds/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/payments/refunds">> = Specific
  const handler = {} as typeof import("../../../src/app/api/payments/refunds/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/payments/webhooks/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/payments/webhooks">> = Specific
  const handler = {} as typeof import("../../../src/app/api/payments/webhooks/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/services/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/services/[id]">> = Specific
  const handler = {} as typeof import("../../../src/app/api/services/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/services/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/services">> = Specific
  const handler = {} as typeof import("../../../src/app/api/services/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/social/comment-reactions/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/social/comment-reactions">> = Specific
  const handler = {} as typeof import("../../../src/app/api/social/comment-reactions/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/social/comments/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/social/comments">> = Specific
  const handler = {} as typeof import("../../../src/app/api/social/comments/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/social/feed/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/social/feed">> = Specific
  const handler = {} as typeof import("../../../src/app/api/social/feed/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/social/posts/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/social/posts">> = Specific
  const handler = {} as typeof import("../../../src/app/api/social/posts/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/social/reactions/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/social/reactions">> = Specific
  const handler = {} as typeof import("../../../src/app/api/social/reactions/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/users/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/users/[id]">> = Specific
  const handler = {} as typeof import("../../../src/app/api/users/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/users/activity/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/users/activity">> = Specific
  const handler = {} as typeof import("../../../src/app/api/users/activity/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/users/change-password/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/users/change-password">> = Specific
  const handler = {} as typeof import("../../../src/app/api/users/change-password/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/users/profile/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/users/profile">> = Specific
  const handler = {} as typeof import("../../../src/app/api/users/profile/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/users/seed-sample-data/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/users/seed-sample-data">> = Specific
  const handler = {} as typeof import("../../../src/app/api/users/seed-sample-data/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/users/stats/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/users/stats">> = Specific
  const handler = {} as typeof import("../../../src/app/api/users/stats/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/ws/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/ws">> = Specific
  const handler = {} as typeof import("../../../src/app/api/ws/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}





// Validate ../../../src/app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../../src/app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
