import type { AnatomyMeshRegion, HumanBlueprintNode } from '@/lib/human-blueprint/schema';

export const ANATOMY_MESH_REGIONS: AnatomyMeshRegion[] = [
  { id: 'brain', name: 'Brain', category: 'organ', meshReference: 'mesh.brain', geometry: 'sphere', position: [0, 2.25, 0.03], scale: [0.42, 0.3, 0.33], color: '#dbeafe' },
  { id: 'heart', name: 'Heart', category: 'organ', meshReference: 'mesh.heart', geometry: 'sphere', position: [0.16, 1.18, 0.24], scale: [0.18, 0.22, 0.18], color: '#f87171' },
  { id: 'left-lung', name: 'Left Lung', category: 'organ', meshReference: 'mesh.left_lung', geometry: 'capsule', position: [-0.34, 1.2, 0.12], scale: [0.2, 0.38, 0.2], color: '#67e8f9' },
  { id: 'right-lung', name: 'Right Lung', category: 'organ', meshReference: 'mesh.right_lung', geometry: 'capsule', position: [0.34, 1.2, 0.12], scale: [0.2, 0.4, 0.22], color: '#22d3ee' },
  { id: 'liver', name: 'Liver', category: 'organ', meshReference: 'mesh.liver', geometry: 'box', position: [0.28, 0.58, 0.2], scale: [0.36, 0.17, 0.22], color: '#fbbf24' },
  { id: 'stomach', name: 'Stomach', category: 'organ', meshReference: 'mesh.stomach', geometry: 'sphere', position: [-0.12, 0.5, 0.2], scale: [0.21, 0.18, 0.16], color: '#fb923c' },
  { id: 'left-kidney', name: 'Left Kidney', category: 'organ', meshReference: 'mesh.left_kidney', geometry: 'capsule', position: [-0.28, 0.18, -0.05], scale: [0.13, 0.2, 0.1], color: '#c084fc' },
  { id: 'right-kidney', name: 'Right Kidney', category: 'organ', meshReference: 'mesh.right_kidney', geometry: 'capsule', position: [0.28, 0.18, -0.05], scale: [0.13, 0.2, 0.1], color: '#a855f7' },
  { id: 'spine', name: 'Spine', category: 'feature', meshReference: 'mesh.spine', geometry: 'capsule', position: [0, 0.78, -0.14], scale: [0.08, 0.72, 0.08], color: '#93c5fd' },
  { id: 'left-eye', name: 'Left Eye', category: 'feature', meshReference: 'mesh.left_eye', geometry: 'sphere', position: [-0.09, 2.31, 0.24], scale: [0.06, 0.06, 0.06], color: '#fde68a' },
  { id: 'right-eye', name: 'Right Eye', category: 'feature', meshReference: 'mesh.right_eye', geometry: 'sphere', position: [0.09, 2.31, 0.24], scale: [0.06, 0.06, 0.06], color: '#fde68a' },
  { id: 'skin', name: 'Skin', category: 'feature', meshReference: 'mesh.skin_field', geometry: 'capsule', position: [0, 1, 0], scale: [0.55, 1.88, 0.52], color: '#f8fafc' },
  { id: 'left-hand', name: 'Left Hand', category: 'feature', meshReference: 'mesh.left_hand', geometry: 'sphere', position: [-0.88, 0.52, 0], scale: [0.1, 0.1, 0.1], color: '#facc15' },
  { id: 'right-hand', name: 'Right Hand', category: 'feature', meshReference: 'mesh.right_hand', geometry: 'sphere', position: [0.88, 0.52, 0], scale: [0.1, 0.1, 0.1], color: '#facc15' },
];

const node = (entry: HumanBlueprintNode): HumanBlueprintNode => entry;

export const HUMAN_BLUEPRINT_LIBRARY: HumanBlueprintNode[] = [
  node({
    id: 'heart',
    name: 'Heart',
    category: 'organ',
    meshReference: 'mesh.heart',
    summary: 'Your heart sustains life by delivering oxygen and nutrients to every tissue in rhythmic waves.',
    function_physical: 'Pumps blood through pulmonary and systemic circulation, maintaining pressure and tissue perfusion.',
    function_emotional_psychological: 'Heart-rate variability reflects stress adaptability and emotional regulation capacity.',
    lifestyle_support: ['Zone 2 cardio most days', 'Consistent sleep-wake rhythm', 'Whole-food anti-inflammatory nutrition'],
    lifestyle_harm: ['Chronic sleep restriction', 'Sedentary behavior', 'Ultra-processed high-sodium diet'],
    reflection_questions: ['Where in my life am I living in constant urgency?', 'What would a calmer pace look like this week?'],
    micro_actions: ['Take a 10-minute post-meal walk', 'Practice 4-6 breathing for 3 minutes'],
    long_term_positive: 'Steady care protects vitality, cognition, and resilience through midlife and beyond.',
    long_term_negative: 'Neglect raises risks for hypertension, vascular damage, and reduced functional years.',
    mythic_identity: 'The Throne of Courage',
    psychological_identity: 'The regulator of safety, trust, and social openness.',
    narrative_voice: 'I set your life rhythm—protect me and your days become expansive, not rushed.',
    transformation_arc: 'From reactive intensity to grounded endurance and emotional steadiness.',
    if_ignore_this: 'Urgency becomes your default identity, shrinking patience and presence.',
    if_honor_this: 'Calm strength becomes your baseline, and relationships feel safer and warmer.',
    relatedNodes: ['lungs', 'cardiovascular-system', 'brain'],
    learningPathOrder: 1,
  }),
  node({
    id: 'brain',
    name: 'Brain',
    category: 'organ',
    meshReference: 'mesh.brain',
    summary: 'Your brain predicts, prioritizes, and integrates experience into meaning and decisions.',
    function_physical: 'Coordinates cognition, sensation, movement, autonomic control, and memory consolidation.',
    function_emotional_psychological: 'Attention quality and cognitive flexibility shape mood, impulse control, and identity stories.',
    lifestyle_support: ['Deep work blocks with device boundaries', 'Regular sleep cycles', 'Learning novelty with retrieval practice'],
    lifestyle_harm: ['Multitasking overload', 'Chronically high stress hormones', 'Sleep debt and alcohol overuse'],
    reflection_questions: ['What story am I rehearsing that is no longer useful?', 'Where can I trade stimulation for clarity?'],
    micro_actions: ['Single-task for 25 minutes', 'Write one reframed thought when stressed'],
    long_term_positive: 'Better executive function supports career, relationships, and wise long-range decisions.',
    long_term_negative: 'Neglect drives cognitive fatigue, poor judgment loops, and emotional volatility.',
    mythic_identity: 'The Architect of Meaning',
    psychological_identity: 'The pattern-maker that determines what feels possible.',
    narrative_voice: 'Feed me signal over noise, and I will build a life of coherent choices.',
    transformation_arc: 'From fragmented attention to deliberate thought and integrated self-authorship.',
    if_ignore_this: 'Noise governs your day and your future gets outsourced to impulse.',
    if_honor_this: 'Clarity compounds; your identity becomes intentional rather than accidental.',
  }),
  node({
    id: 'lungs',
    name: 'Lungs',
    category: 'organ',
    meshReference: 'mesh.left_lung|mesh.right_lung',
    summary: 'Your lungs exchange gases and regulate the pace of your internal state through breath.',
    function_physical: 'Enable oxygen uptake, carbon dioxide elimination, and acid-base balance.',
    function_emotional_psychological: 'Breath cadence modulates arousal, panic thresholds, and felt safety.',
    lifestyle_support: ['Daily nasal breathing walks', 'Posture expansion breaks', 'Air quality and hydration care'],
    lifestyle_harm: ['Shallow chest breathing', 'Smoking and vapor inhalation', 'Persistent slumped posture'],
    reflection_questions: ['When stress rises, does my breath tighten?', 'What changes when I exhale slowly?'],
    micro_actions: ['Five cycles of 4-second inhale / 6-second exhale', 'Two posture resets each work hour'],
    long_term_positive: 'Improved respiratory efficiency supports endurance, calmness, and stress recovery.',
    long_term_negative: 'Neglect drives fatigue, anxiety reactivity, and reduced aerobic capacity.',
    mythic_identity: 'The Gatekeepers of Presence',
    psychological_identity: 'The bridge between body alarms and conscious regulation.',
    narrative_voice: 'When you breathe with intention, I return you to the present moment.',
    transformation_arc: 'From breath-holding under pressure to rhythmic presence in challenge.',
    if_ignore_this: 'Stress hijacks your physiology before awareness can intervene.',
    if_honor_this: 'Presence becomes trainable, and resilience appears in real time.',
  }),
  node({
    id: 'liver',
    name: 'Liver',
    category: 'organ',
    meshReference: 'mesh.liver',
    summary: 'Your liver is the metabolic command center for detoxification, nutrient transformation, and energy balance.',
    function_physical: 'Processes nutrients, supports glucose regulation, produces bile, and clears metabolic byproducts.',
    function_emotional_psychological: 'Energy volatility from metabolic strain can amplify irritability and low motivation.',
    lifestyle_support: ['Protein-forward balanced meals', 'Strength training 2-3x weekly', 'Alcohol boundaries'],
    lifestyle_harm: ['Excess alcohol', 'High-fructose ultra-processed intake', 'Chronic inactivity'],
    reflection_questions: ['What habits make my energy unstable?', 'Which evening choice helps tomorrow’s clarity?'],
    micro_actions: ['Build one plate with protein-fiber-color', 'Schedule two alcohol-free social alternatives'],
    long_term_positive: 'Metabolic health preserves energy, cognition, and cardiovascular protection over decades.',
    long_term_negative: 'Neglect can lead to fatty liver progression, insulin resistance, and systemic inflammation.',
    mythic_identity: 'The Alchemist of Renewal',
    psychological_identity: 'The converter of excess into usable order.',
    narrative_voice: 'Give me clean inputs and rhythm, and I will return stable power.',
    transformation_arc: 'From biochemical overload to metabolic clarity and sustainable energy.',
    if_ignore_this: 'Energy becomes erratic and long-term disease risk rises quietly.',
    if_honor_this: 'Your days feel cleaner, steadier, and more directed.',
  }),
  node({
    id: 'stomach',
    name: 'Stomach',
    category: 'organ',
    meshReference: 'mesh.stomach',
    summary: 'Your stomach initiates digestion by mechanically and chemically preparing food for nutrient extraction.',
    function_physical: 'Stores food briefly, secretes acid and enzymes, and meters chyme into the small intestine.',
    function_emotional_psychological: 'Stress can alter gastric motility and sensitivity, amplifying discomfort and appetite dysregulation.',
    lifestyle_support: ['Eat at a deliberate pace', 'Prioritize whole foods over irritant-heavy processed meals', 'Allow a calm window before and after meals'],
    lifestyle_harm: ['Rapid stress-eating', 'Frequent late heavy meals', 'Excess alcohol and highly irritant food patterns'],
    reflection_questions: ['Do I eat in urgency or in awareness?', 'What meal habit consistently leaves me feeling better two hours later?'],
    micro_actions: ['Take three slow breaths before your next meal', 'Chew each bite longer for one meal today'],
    long_term_positive: 'Stomach-aware habits improve digestive comfort, nutrient use, and day-long energy stability.',
    long_term_negative: 'Neglect can reinforce reflux patterns, gastric irritation, and chronic digestive unpredictability.',
    mythic_identity: 'The Crucible of Intake',
    psychological_identity: 'The first gate where experience is received, softened, and processed.',
    narrative_voice: 'Give me steadiness and I turn nourishment into usable strength.',
    transformation_arc: 'From rushed consumption to intentional receiving and integration.',
    if_ignore_this: 'What you consume governs you through discomfort and reactivity.',
    if_honor_this: 'Your nourishment becomes a daily act of stability and discernment.',
  }),
  node({
    id: 'kidneys',
    name: 'Kidneys',
    category: 'organ',
    meshReference: 'mesh.left_kidney|mesh.right_kidney',
    summary: 'Your kidneys continuously filter blood, tune electrolytes, and help regulate pressure and hydration.',
    function_physical: 'Filter plasma, balance sodium/potassium, regulate fluid volume and blood pressure signaling.',
    function_emotional_psychological: 'Hydration and electrolyte balance influence energy, concentration, and stress tolerance.',
    lifestyle_support: ['Consistent hydration', 'Blood pressure monitoring', 'Moderate sodium and processed food intake'],
    lifestyle_harm: ['Chronic dehydration', 'Uncontrolled hypertension', 'Excess NSAID overuse'],
    reflection_questions: ['Do I hydrate proactively or only when depleted?', 'How often do I check pressure trends?'],
    micro_actions: ['Start day with water before caffeine', 'Track blood pressure 3 days this week'],
    long_term_positive: 'Kidney care protects cardiovascular stability and reduces chronic disease burden.',
    long_term_negative: 'Neglect can progress to renal strain, fluid imbalance, and escalating health complexity.',
    mythic_identity: 'The Keepers of Purity',
    psychological_identity: 'The internal boundary stewards—what stays, what leaves.',
    narrative_voice: 'Respect your internal balance, and I keep your system clean and steady.',
    transformation_arc: 'From depletion cycles to fluid intelligence and physiological steadiness.',
    if_ignore_this: 'Fatigue and pressure dysregulation accumulate with little warning.',
    if_honor_this: 'You feel clear, stable, and physically dependable.',
  }),
  node({
    id: 'spine',
    name: 'Spine',
    category: 'feature',
    meshReference: 'mesh.spine',
    summary: 'Your spine anchors movement, protects neural pathways, and encodes posture as behavior.',
    function_physical: 'Supports structure, transmits force, and protects spinal cord communication.',
    function_emotional_psychological: 'Posture feeds confidence signals and stress appraisal loops.',
    lifestyle_support: ['Daily mobility micro-breaks', 'Strengthening posterior chain', 'Ergonomic workstation setup'],
    lifestyle_harm: ['Prolonged static sitting', 'Weak core and glutes', 'Ignoring chronic pain cues'],
    reflection_questions: ['What does my posture communicate to myself?', 'Where do I collapse under pressure?'],
    micro_actions: ['2-minute standing reset every 45 minutes', 'Three sets of bodyweight hinge practice'],
    long_term_positive: 'Spinal integrity preserves mobility, confidence, and independent living capacity.',
    long_term_negative: 'Neglect increases pain cycles, movement fear, and productivity decline.',
    mythic_identity: 'The Pillar of Integrity',
    psychological_identity: 'The embodied axis of conviction and follow-through.',
    narrative_voice: 'Stand with me and your choices gain structure.',
    transformation_arc: 'From collapse and compensation to alignment and capable movement.',
    if_ignore_this: 'Pain narrows your world and erodes daily confidence.',
    if_honor_this: 'Strength and dignity become visible in every room you enter.',
  }),
  node({
    id: 'eyes',
    name: 'Eyes',
    category: 'feature',
    meshReference: 'mesh.left_eye|mesh.right_eye',
    summary: 'Your eyes direct attention and shape perception, learning, and social connection.',
    function_physical: 'Convert light to neural signals and coordinate depth, focus, and visual tracking.',
    function_emotional_psychological: 'Attention targets can intensify anxiety or cultivate grounded observation.',
    lifestyle_support: ['20-20-20 visual breaks', 'Morning daylight exposure', 'Sleep-supportive evening light limits'],
    lifestyle_harm: ['Late-night blue-light overload', 'No visual rest from screens', 'Poor ambient lighting'],
    reflection_questions: ['What am I repeatedly choosing to look at?', 'Does my visual environment calm or agitate me?'],
    micro_actions: ['Look at distant horizon for 20 seconds each hour', 'Dim screens one hour before sleep'],
    long_term_positive: 'Visual hygiene supports cognition, sleep quality, and sustained focus.',
    long_term_negative: 'Neglect contributes to eye strain, headaches, and attention fatigue.',
    mythic_identity: 'The Windows of Discernment',
    psychological_identity: 'The selectors of what enters conscious priority.',
    narrative_voice: 'Where you place your gaze, your life will follow.',
    transformation_arc: 'From distracted scanning to intentional seeing.',
    if_ignore_this: 'Attention fragments and mental fatigue grows louder.',
    if_honor_this: 'Your focus becomes cleaner and your choices more deliberate.',
  }),
  node({
    id: 'skin',
    name: 'Skin',
    category: 'feature',
    meshReference: 'mesh.skin_field',
    summary: 'Your skin is your boundary layer: protection, sensation, temperature regulation, and immune signaling.',
    function_physical: 'Acts as barrier, sensory interface, and thermoregulation surface.',
    function_emotional_psychological: 'Skin sensitivity can mirror stress load and inflammation states.',
    lifestyle_support: ['Hydration and nutrient-dense foods', 'Gentle cleansing and sun protection', 'Stress and sleep regulation'],
    lifestyle_harm: ['Chronic UV overexposure', 'Harsh irritant routines', 'Dehydration and high stress'],
    reflection_questions: ['How do I treat my boundaries with myself and others?', 'What does irritation in my life look like physically?'],
    micro_actions: ['Use SPF when UV is high', 'Apply a simple barrier-support routine nightly'],
    long_term_positive: 'Skin stewardship supports confidence, comfort, and reduced inflammatory burden.',
    long_term_negative: 'Neglect leads to barrier disruption, accelerated aging, and preventable irritation.',
    mythic_identity: 'The Living Boundary',
    psychological_identity: 'The interface between inner state and outer world.',
    narrative_voice: 'Protect my boundary, and I will protect your contact with the world.',
    transformation_arc: 'From reactive surface to resilient boundary intelligence.',
    if_ignore_this: 'Irritation rises and resilience falls at your edges.',
    if_honor_this: 'You feel protected, calm, and comfortably present.',
  }),
  node({
    id: 'hands',
    name: 'Hands',
    category: 'feature',
    meshReference: 'mesh.left_hand|mesh.right_hand',
    summary: 'Your hands convert intention into action, craft, care, and contribution.',
    function_physical: 'Enable fine motor control, grip strength, and sensory-rich object interaction.',
    function_emotional_psychological: 'Hands express agency: doing, repairing, creating, and comforting.',
    lifestyle_support: ['Grip and mobility training', 'Regular breaks from repetitive strain', 'Creative manual practice'],
    lifestyle_harm: ['Repetitive overuse without recovery', 'Poor wrist ergonomics', 'Sedentary non-use of dexterity'],
    reflection_questions: ['What am I building with my hands this season?', 'Where can I replace passive scrolling with creation?'],
    micro_actions: ['Two minutes of hand mobility daily', 'One tangible creation session weekly'],
    long_term_positive: 'Hand function preserves independence, confidence, and craft capacity.',
    long_term_negative: 'Neglect can reduce dexterity, increase pain, and limit autonomy.',
    mythic_identity: 'The Artisans of Reality',
    psychological_identity: 'The execution channel for identity commitments.',
    narrative_voice: 'Give me deliberate work and your values become visible.',
    transformation_arc: 'From passive consumption to embodied creation.',
    if_ignore_this: 'Intentions stay abstract and your agency weakens.',
    if_honor_this: 'Your life becomes shaped by action, not only thought.',
  }),
  node({
    id: 'nervous-system',
    name: 'Nervous System',
    category: 'system',
    meshReference: 'system.nervous',
    summary: 'Your signaling network coordinates sensation, thought, movement, and autonomic response.',
    function_physical: 'Transmits electrical and chemical signals across central and peripheral pathways.',
    function_emotional_psychological: 'Defines stress reactivity, recovery speed, and baseline arousal.',
    lifestyle_support: ['Consistent sleep', 'Parasympathetic breathing', 'Intentional recovery windows'],
    lifestyle_harm: ['Continuous digital overstimulation', 'Uninterrupted stress exposure', 'No restorative downtime'],
    reflection_questions: ['How often do I intentionally downshift my system?', 'What habits keep me in high alert?'],
    micro_actions: ['90-second physiological sigh practice', 'One no-notification focus block daily'],
    long_term_positive: 'Better regulation improves clarity, emotional flexibility, and health outcomes.',
    long_term_negative: 'Dysregulation drives anxiety loops, burnout, and impaired decision quality.',
    mythic_identity: 'The Lightning Web',
    psychological_identity: 'The threshold manager for safety and threat detection.',
    narrative_voice: 'Regulate me, and your mind becomes an ally instead of an alarm.',
    transformation_arc: 'From chronic hypervigilance to adaptive self-regulation.',
    if_ignore_this: 'Your baseline drifts toward overload and reactivity.',
    if_honor_this: 'Calm responsiveness replaces chronic urgency.',
  }),
  node({
    id: 'circulatory-system',
    name: 'Circulatory System',
    category: 'system',
    meshReference: 'system.circulatory',
    summary: 'Your circulation distributes oxygen, nutrients, hormones, and immune signals everywhere.',
    function_physical: 'Moves blood through arteries, capillaries, and veins for delivery and return.',
    function_emotional_psychological: 'Circulatory fitness supports stable mood and cognitive stamina.',
    lifestyle_support: ['Regular movement throughout day', 'Cardiovascular training', 'Adequate hydration'],
    lifestyle_harm: ['Long sedentary blocks', 'Smoking', 'Poor metabolic control'],
    reflection_questions: ['Where is stagnation showing up in my routines?', 'What movement pattern can I sustain daily?'],
    micro_actions: ['Stand or walk 5 minutes every hour', 'Two short cardio sessions this week'],
    long_term_positive: 'Strong circulation protects brain, heart, and whole-body longevity.',
    long_term_negative: 'Neglect increases vascular rigidity and systemic disease risk.',
    mythic_identity: 'The River of Life',
    psychological_identity: 'The momentum channel for effort and renewal.',
    narrative_voice: 'Keep me flowing and your life force stays available.',
    transformation_arc: 'From stagnation to sustained vitality.',
    if_ignore_this: 'Sluggish flow becomes normal and vitality fades.',
    if_honor_this: 'Energy and emotional steadiness become easier to maintain.',
  }),
  node({
    id: 'respiratory-system',
    name: 'Respiratory System',
    category: 'system',
    meshReference: 'system.respiratory',
    summary: 'Your respiratory system fuels cellular energy and tunes nervous-system state through breath.',
    function_physical: 'Ventilation and diffusion provide oxygen and remove carbon dioxide.',
    function_emotional_psychological: 'Breath habits directly influence panic sensitivity and composure.',
    lifestyle_support: ['Daily aerobic movement', 'Posture and rib mobility', 'Low-irritant air environments'],
    lifestyle_harm: ['Inactivity', 'Pollutant exposure', 'Chronic mouth breathing'],
    reflection_questions: ['Do I breathe to cope, or to perform?', 'When pressure rises, what does my breath do first?'],
    micro_actions: ['Three breath resets before major meetings', 'Nasal breathing walk after meals'],
    long_term_positive: 'Respiratory conditioning improves resilience and stress recovery.',
    long_term_negative: 'Neglect weakens endurance and amplifies anxiety cascades.',
    mythic_identity: 'The Winds of Presence',
    psychological_identity: 'The rhythm engine of composure.',
    narrative_voice: 'Use me consciously and pressure becomes navigable.',
    transformation_arc: 'From shallow survival breathing to intentional regulation.',
    if_ignore_this: 'Stress reactivity accelerates faster than awareness.',
    if_honor_this: 'You stay present under challenge.',
  }),
  node({
    id: 'endocrine-system',
    name: 'Endocrine System',
    category: 'system',
    meshReference: 'system.endocrine',
    summary: 'Your hormone network coordinates growth, metabolism, stress adaptation, and reproductive timing.',
    function_physical: 'Hormonal signaling governs energy use, appetite, sleep cues, and recovery.',
    function_emotional_psychological: 'Hormone rhythm disruptions affect mood stability and motivation.',
    lifestyle_support: ['Circadian-aligned sleep', 'Strength training', 'Protein-rich regular meals'],
    lifestyle_harm: ['Irregular sleep timing', 'Chronic high stress', 'Extreme dieting cycles'],
    reflection_questions: ['Are my routines aligned with day-night biology?', 'Which habit destabilizes my energy most?'],
    micro_actions: ['Morning outdoor light exposure', 'Consistent sleep window for 7 days'],
    long_term_positive: 'Hormonal rhythm supports fertility, mood, and metabolic health.',
    long_term_negative: 'Dysregulation can impair mood, body composition, and long-term vitality.',
    mythic_identity: 'The Inner Constellation',
    psychological_identity: 'The timing intelligence behind mood and drive.',
    narrative_voice: 'Honor rhythm and I return reliable energy.',
    transformation_arc: 'From hormonal chaos to biological coherence.',
    if_ignore_this: 'Mood and energy become difficult to predict or trust.',
    if_honor_this: 'You gain steady momentum with fewer crashes.',
  }),
  node({
    id: 'digestive-system',
    name: 'Digestive System',
    category: 'system',
    meshReference: 'system.digestive',
    summary: 'Your digestive system extracts fuel and building blocks from what you consume.',
    function_physical: 'Breaks down food, absorbs nutrients, and coordinates gut motility and elimination.',
    function_emotional_psychological: 'Gut-brain communication influences mood, focus, and stress responses.',
    lifestyle_support: ['Fiber-rich whole foods', 'Regular meal timing', 'Hydration and mindful eating pace'],
    lifestyle_harm: ['Highly processed food patterns', 'Erratic meal timing', 'Chronic overeating under stress'],
    reflection_questions: ['Do I eat in a stressed state most days?', 'Which foods consistently energize me?'],
    micro_actions: ['Eat one meal slowly without screens', 'Add one extra high-fiber food today'],
    long_term_positive: 'Digestive consistency supports immunity, cognition, and stable energy.',
    long_term_negative: 'Neglect contributes to inflammation, discomfort, and reduced quality of life.',
    mythic_identity: 'The Forge of Nourishment',
    psychological_identity: 'The integrator of intake into usable strength.',
    narrative_voice: 'Choose inputs with care and I will convert them into capacity.',
    transformation_arc: 'From reactive eating to intentional nourishment.',
    if_ignore_this: 'Inflammation and fatigue quietly define your baseline.',
    if_honor_this: 'Energy and mood become more predictable and resilient.',
  }),
  node({
    id: 'urinary-system',
    name: 'Urinary System',
    category: 'system',
    meshReference: 'system.urinary',
    summary: 'Your urinary system maintains fluid chemistry and removes dissolved metabolic waste.',
    function_physical: 'Filters blood products and regulates electrolyte concentration and fluid output.',
    function_emotional_psychological: 'Hydration state affects concentration, mood, and stress tolerance.',
    lifestyle_support: ['Steady hydration', 'Balanced electrolyte intake', 'Blood pressure care'],
    lifestyle_harm: ['Dehydration cycles', 'Excess sodium patterns', 'Ignoring blood pressure trends'],
    reflection_questions: ['Do I rely on thirst alone to hydrate?', 'What routine protects my internal balance?'],
    micro_actions: ['Pre-plan daily water intervals', 'Review blood pressure once weekly'],
    long_term_positive: 'Good urinary health preserves cardiovascular and renal resilience.',
    long_term_negative: 'Neglect can accelerate chronic kidney burden and systemic strain.',
    mythic_identity: 'The Purification Stream',
    psychological_identity: 'The discipline of internal order.',
    narrative_voice: 'Consistency protects me more than intensity.',
    transformation_arc: 'From neglect of basics to disciplined stability.',
    if_ignore_this: 'Small imbalances compound into larger health burdens.',
    if_honor_this: 'Your body runs cleaner and steadier.',
  }),
  node({
    id: 'immune-system',
    name: 'Immune System',
    category: 'system',
    meshReference: 'system.immune',
    summary: 'Your immune system protects against threats while balancing inflammation and tissue repair.',
    function_physical: 'Detects and responds to pathogens, clears damaged cells, and supports healing.',
    function_emotional_psychological: 'Chronic stress and poor recovery can dysregulate immune response.',
    lifestyle_support: ['Sleep sufficiency', 'Nutrient-dense diet', 'Stress load management'],
    lifestyle_harm: ['Sleep deprivation', 'Persistent high stress', 'Nutrient-poor dietary patterns'],
    reflection_questions: ['Do my routines support recovery as much as effort?', 'What weakens my baseline resilience?'],
    micro_actions: ['Prioritize one extra hour of sleep opportunity', 'Add one recovery ritual nightly'],
    long_term_positive: 'Balanced immunity supports longevity and faster rebound from stressors.',
    long_term_negative: 'Neglect elevates infection risk and chronic inflammatory burden.',
    mythic_identity: 'The Guardians of Renewal',
    psychological_identity: 'The boundary protectors against internal and external threats.',
    narrative_voice: 'Recover well, and I defend you with precision.',
    transformation_arc: 'From depletion and susceptibility to robust adaptive defense.',
    if_ignore_this: 'Frequent setbacks interrupt your momentum.',
    if_honor_this: 'You recover faster and sustain progress longer.',
  }),
  node({
    id: 'sleep-architecture',
    name: 'Sleep Architecture',
    category: 'feature',
    meshReference: 'feature.sleep_cycle',
    summary: 'Sleep architecture cycles through stages that restore body systems and consolidate learning.',
    function_physical: 'Supports hormonal reset, memory integration, cellular repair, and metabolic regulation.',
    function_emotional_psychological: 'Poor sleep intensifies emotional reactivity and cognitive errors.',
    lifestyle_support: ['Consistent bedtime', 'Evening light reduction', 'Caffeine timing boundaries'],
    lifestyle_harm: ['Irregular schedules', 'Late stimulation', 'Sleep disruption from screens and stress'],
    reflection_questions: ['What evening pattern steals tomorrow’s focus?', 'What bedtime ritual reliably calms me?'],
    micro_actions: ['Set fixed wake time for 7 days', 'Create 20-minute wind-down sequence'],
    long_term_positive: 'Stable sleep multiplies physical recovery and decision quality.',
    long_term_negative: 'Neglect drives metabolic risk, mood instability, and performance decline.',
    mythic_identity: 'The Night Workshop',
    psychological_identity: 'The unseen process where identity is neurologically reinforced.',
    narrative_voice: 'Guard my timing and your future self arrives stronger.',
    transformation_arc: 'From exhausted reaction to recovered intention.',
    if_ignore_this: 'Every other system pays the debt.',
    if_honor_this: 'Everything else becomes easier to improve.',
  }),
];

export const HUMAN_BLUEPRINT_LIBRARY_BY_ID = Object.fromEntries(
  HUMAN_BLUEPRINT_LIBRARY.map((entry) => [entry.id, entry])
) as Record<string, HumanBlueprintNode>;

export const BLUEPRINT_SYSTEM_IDS = HUMAN_BLUEPRINT_LIBRARY.filter((entry) => entry.category === 'system').map((entry) => entry.id);
export const BLUEPRINT_ORGAN_IDS = HUMAN_BLUEPRINT_LIBRARY.filter((entry) => entry.category === 'organ').map((entry) => entry.id);
export const BLUEPRINT_FEATURE_IDS = HUMAN_BLUEPRINT_LIBRARY.filter((entry) => entry.category === 'feature').map((entry) => entry.id);
