import fs from 'fs/promises';
import path from 'path';
import sharp from 'sharp';

type Route = 'a' | 'b' | 'c';
type Variant = 'master' | 'mono' | 'invert';

const size = 256;
const padding = 48;
const cellGap = 28;
const headerHeight = 92;
const footerHeight = 40;
const cellSize = size;

const routes: Route[] = ['a', 'b', 'c'];
const routeLabels: Record<Route, string> = {
  a: 'Route A — Arc',
  b: 'Route B — Core',
  c: 'Route C — Monogram',
};

const variants: Variant[] = ['master', 'mono', 'invert'];
const variantLabels: Record<Variant, string> = {
  master: 'Master',
  mono: 'Mono',
  invert: 'Invert',
};

const workspaceRoot = process.cwd();
const pngDir = path.join(workspaceRoot, 'docs', 'brand', 'logo-drafts', 'routes-v1', 'png', String(size));
const outputDir = path.join(workspaceRoot, 'docs', 'brand', 'logo-drafts', 'routes-v1', 'png', 'preview');
const outputFile = path.join(outputDir, 'aurora-routes-v2-sheet.png');

function textSvg(text: string, width: number, height: number, options?: { size?: number; weight?: number; color?: string; align?: 'left' | 'center' }) {
  const fontSize = options?.size ?? 18;
  const fontWeight = options?.weight ?? 600;
  const color = options?.color ?? '#0F172A';
  const align = options?.align ?? 'left';
  const x = align === 'center' ? '50%' : '0';
  const anchor = align === 'center' ? 'middle' : 'start';

  const svg = `
  <svg width="${width}" height="${height}" viewBox="0 0 ${width} ${height}" xmlns="http://www.w3.org/2000/svg">
    <text x="${x}" y="${Math.round(height * 0.72)}" fill="${color}" font-size="${fontSize}" font-family="Inter, Segoe UI, Arial, sans-serif" font-weight="${fontWeight}" text-anchor="${anchor}">${text}</text>
  </svg>`;
  return Buffer.from(svg);
}

async function ensureDir(dirPath: string) {
  await fs.mkdir(dirPath, { recursive: true });
}

function sourcePath(route: Route, variant: Variant) {
  const routeName = route === 'a' ? 'arc' : route === 'b' ? 'core' : 'monogram';
  return path.join(pngDir, `aurora-route-${route}-${routeName}-${variant}.png`);
}

async function verifyInputs() {
  for (const route of routes) {
    for (const variant of variants) {
      const src = sourcePath(route, variant);
      try {
        await fs.access(src);
      } catch {
        throw new Error(`Missing source PNG: ${src}`);
      }
    }
  }
}

async function generatePreviewSheet() {
  await verifyInputs();
  await ensureDir(outputDir);

  const width = padding * 2 + variants.length * cellSize + (variants.length - 1) * cellGap;
  const height = headerHeight + padding + routes.length * cellSize + (routes.length - 1) * cellGap + footerHeight;

  const composites: sharp.OverlayOptions[] = [];

  composites.push({
    input: textSvg('Aurora Logo Routes — v2 Preview', width - padding * 2, 42, {
      size: 28,
      weight: 700,
      color: '#0F172A',
      align: 'left',
    }),
    left: padding,
    top: 24,
  });

  composites.push({
    input: textSvg('A/B/C × Master/Mono/Invert (256px source)', width - padding * 2, 30, {
      size: 16,
      weight: 500,
      color: '#475569',
      align: 'left',
    }),
    left: padding,
    top: 56,
  });

  for (let col = 0; col < variants.length; col += 1) {
    const x = padding + col * (cellSize + cellGap);
    composites.push({
      input: textSvg(variantLabels[variants[col]], cellSize, 26, {
        size: 16,
        weight: 650,
        color: '#334155',
        align: 'center',
      }),
      left: x,
      top: headerHeight,
    });
  }

  for (let row = 0; row < routes.length; row += 1) {
    const y = headerHeight + padding + row * (cellSize + cellGap);

    composites.push({
      input: textSvg(routeLabels[routes[row]], 180, 30, {
        size: 15,
        weight: 650,
        color: '#1E293B',
        align: 'left',
      }),
      left: 10,
      top: y + 10,
    });

    for (let col = 0; col < variants.length; col += 1) {
      const x = padding + col * (cellSize + cellGap);
      const src = sourcePath(routes[row], variants[col]);

      composites.push({
        input: src,
        left: x,
        top: y,
      });
    }
  }

  composites.push({
    input: textSvg('Generated by scripts/export-logo-routes-preview-v1.ts', width - padding * 2, 20, {
      size: 12,
      weight: 500,
      color: '#64748B',
      align: 'left',
    }),
    left: padding,
    top: height - 26,
  });

  await sharp({
    create: {
      width,
      height,
      channels: 4,
      background: '#F8FAFC',
    },
  })
    .composite(composites)
    .png({ compressionLevel: 9 })
    .toFile(outputFile);

  console.log(`Route preview sheet generated: ${outputFile}`);
}

generatePreviewSheet().catch((error) => {
  console.error('Failed generating route preview sheet:', error);
  process.exit(1);
});
